---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
- name: ubuntu-15.10
  # driver_config:
  #   box: opscode-ubuntu-12.10
  #   box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.10_provisionerless.box
  # run_list:
  # - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[teamcity_server_test]
- name: agent
  run_list:
    - recipe[teamcity_server::build_agent]
