---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
- name: ubuntu-14.04
- name: ubuntu-15.10

suites:
- name: default
  run_list:
  - recipe[minitest-handler]
  - recipe[teamcity_server_test]
- name: agent
  run_list:
    - recipe[teamcity_server::build_agent]
